const { chromium } = require("playwright");
const HIDE=`#vqbFlow,#mob-tut-overlay,#mobBarTutorial,#firstLaunchOverlay,#vqOnboardingOverlay{display:none !important;}`;
(async()=>{const b=await chromium.launch();const pg=await(await b.newContext()).newPage();
const errs=[];pg.on("console",m=>{if(m.type()==="error")errs.push(m.text().slice(0,140))});
pg.on("response",r=>{if(r.status()>=400)errs.push("HTTP "+r.status()+" "+r.url().slice(0,110))});
await pg.goto("http://127.0.0.1:8791/?vqdev=1",{waitUntil:"domcontentloaded"});
await pg.addStyleTag({content:HIDE});
await pg.waitForFunction(()=>document.getElementById("authLoginSubmitBtn"),{timeout:20000});
await pg.evaluate(()=>{const s=(el,v)=>{const p=el.tagName==="SELECT"?HTMLSelectElement:HTMLInputElement;
 Object.getOwnPropertyDescriptor(p.prototype,"value").set.call(el,v);
 el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));};
 s(document.getElementById("authLoginGrade"),"H3");s(document.getElementById("authLoginNickname"),"tester");
 s(document.getElementById("authLoginPassword"),"Abcd1234");document.getElementById("authLoginSubmitBtn").click();});
await pg.waitForFunction(()=>document.body.getAttribute("data-ui-v2")==="1",{timeout:30000});
await pg.waitForTimeout(9000);
const by={};errs.forEach(e=>{const k=e.replace(/\?.*$/,"").replace(/[0-9a-f-]{8,}/g,":id");by[k]=(by[k]||0)+1});
console.log("合計",errs.length,"件");
Object.keys(by).sort((a,b)=>by[b]-by[a]).slice(0,8).forEach(k=>console.log("  "+String(by[k]).padStart(3)+"回  "+k));
await b.close();})().catch(e=>{console.error(e);process.exit(1)});
